In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']

In [3]:
my_data = ['10','20','30']

In [4]:
arr1 = np.array([25,89,69])

In [5]:
d = {'x':89,'y':100,'z':56}

In [6]:
my_data

['10', '20', '30']

In [7]:
ser1 = pd.Series(my_data)

In [8]:
ser1

0    10
1    20
2    30
dtype: object

In [9]:
type(ser1)

pandas.core.series.Series

In [10]:
ser1 = pd.Series(my_data,index=labels)

In [11]:
ser1

a    10
b    20
c    30
dtype: object

In [12]:
ser2 = pd.Series(d)

In [13]:
ser2

x     89
y    100
z     56
dtype: int64

In [14]:
d

{'x': 89, 'y': 100, 'z': 56}

In [15]:
data = np.random.rand(20)

In [16]:
data

array([0.4544187 , 0.32630772, 0.01549259, 0.92203483, 0.94314439,
       0.05417598, 0.5190346 , 0.99572436, 0.00756338, 0.83115811,
       0.21227716, 0.11584687, 0.21108222, 0.27188145, 0.1572955 ,
       0.14024082, 0.96486666, 0.4559626 , 0.63511399, 0.77020901])

In [17]:
data.shape

(20,)

In [18]:
data = data.reshape(5,4)

In [19]:
data

array([[0.4544187 , 0.32630772, 0.01549259, 0.92203483],
       [0.94314439, 0.05417598, 0.5190346 , 0.99572436],
       [0.00756338, 0.83115811, 0.21227716, 0.11584687],
       [0.21108222, 0.27188145, 0.1572955 , 0.14024082],
       [0.96486666, 0.4559626 , 0.63511399, 0.77020901]])

In [20]:
data.shape

(5, 4)

In [21]:
data

array([[0.4544187 , 0.32630772, 0.01549259, 0.92203483],
       [0.94314439, 0.05417598, 0.5190346 , 0.99572436],
       [0.00756338, 0.83115811, 0.21227716, 0.11584687],
       [0.21108222, 0.27188145, 0.1572955 , 0.14024082],
       [0.96486666, 0.4559626 , 0.63511399, 0.77020901]])

In [22]:
df = pd.DataFrame(data)

In [23]:
df

0         1         2         3
0  0.454419  0.326308  0.015493  0.922035
1  0.943144  0.054176  0.519035  0.995724
2  0.007563  0.831158  0.212277  0.115847
3  0.211082  0.271881  0.157295  0.140241
4  0.964867  0.455963  0.635114  0.770209

In [24]:
df = pd.DataFrame(data,columns=['tejaswini','aashima','yogesh','pravin'])

In [25]:
df

tejaswini   aashima    yogesh    pravin
0   0.454419  0.326308  0.015493  0.922035
1   0.943144  0.054176  0.519035  0.995724
2   0.007563  0.831158  0.212277  0.115847
3   0.211082  0.271881  0.157295  0.140241
4   0.964867  0.455963  0.635114  0.770209

In [26]:
df = pd.DataFrame(data,columns=['tejaswini','aashima','yogesh','pravin'],index=['a','c','f','g','t'])

In [27]:
df

tejaswini   aashima    yogesh    pravin
a   0.454419  0.326308  0.015493  0.922035
c   0.943144  0.054176  0.519035  0.995724
f   0.007563  0.831158  0.212277  0.115847
g   0.211082  0.271881  0.157295  0.140241
t   0.964867  0.455963  0.635114  0.770209

In [28]:
df1 = pd.read_csv('sat.csv')

In [29]:
df1

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [29]:
df3 = pd.read_csv('test.csv')

In [30]:
df3

name  salary
0  aashima    2000
1     dany    1000
2   pravin    4500
3     isha    2569
4   yogesh    4569

In [31]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [32]:
df.shape

(5, 4)

In [33]:
df['yogesh']

a    0.556951
c    0.680753
f    0.202435
g    0.478534
t    0.989024
Name: yogesh, dtype: float64

In [34]:
df['aashima']

a    0.332858
c    0.883521
f    0.469042
g    0.548193
t    0.209079
Name: aashima, dtype: float64

In [35]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [36]:
df[['aashima','yogesh']]

aashima    yogesh
a  0.332858  0.556951
c  0.883521  0.680753
f  0.469042  0.202435
g  0.548193  0.478534
t  0.209079  0.989024

In [37]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [38]:
df['isha'] = [25,6,25,78,96]

In [39]:
df

tejaswini   aashima    yogesh    pravin  isha
a   0.339868  0.332858  0.556951  0.839451    25
c   0.777873  0.883521  0.680753  0.104139     6
f   0.754932  0.469042  0.202435  0.940436    25
g   0.351099  0.548193  0.478534  0.201357    78
t   0.582357  0.209079  0.989024  0.314500    96

In [40]:
df['dany'] = [25,6,4,7,8]

In [41]:
df

tejaswini   aashima    yogesh    pravin  isha  dany
a   0.339868  0.332858  0.556951  0.839451    25    25
c   0.777873  0.883521  0.680753  0.104139     6     6
f   0.754932  0.469042  0.202435  0.940436    25     4
g   0.351099  0.548193  0.478534  0.201357    78     7
t   0.582357  0.209079  0.989024  0.314500    96     8

In [42]:
df.drop('dany',axis=1)

tejaswini   aashima    yogesh    pravin  isha
a   0.339868  0.332858  0.556951  0.839451    25
c   0.777873  0.883521  0.680753  0.104139     6
f   0.754932  0.469042  0.202435  0.940436    25
g   0.351099  0.548193  0.478534  0.201357    78
t   0.582357  0.209079  0.989024  0.314500    96

In [44]:
df

tejaswini   aashima    yogesh    pravin  isha  dany
a   0.339868  0.332858  0.556951  0.839451    25    25
c   0.777873  0.883521  0.680753  0.104139     6     6
f   0.754932  0.469042  0.202435  0.940436    25     4
g   0.351099  0.548193  0.478534  0.201357    78     7
t   0.582357  0.209079  0.989024  0.314500    96     8

In [45]:
df.drop('dany',axis=1,inplace=True)

In [46]:
df

tejaswini   aashima    yogesh    pravin  isha
a   0.339868  0.332858  0.556951  0.839451    25
c   0.777873  0.883521  0.680753  0.104139     6
f   0.754932  0.469042  0.202435  0.940436    25
g   0.351099  0.548193  0.478534  0.201357    78
t   0.582357  0.209079  0.989024  0.314500    96

In [47]:
df.drop('isha',axis=1,inplace=True)

In [48]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [49]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [50]:
df.loc['a']

tejaswini    0.339868
aashima      0.332858
yogesh       0.556951
pravin       0.839451
Name: a, dtype: float64

In [51]:
df.iloc[0]

tejaswini    0.339868
aashima      0.332858
yogesh       0.556951
pravin       0.839451
Name: a, dtype: float64

In [52]:
df.loc[['c','f','g']]

tejaswini   aashima    yogesh    pravin
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357

In [53]:
df.iloc[1:4]

tejaswini   aashima    yogesh    pravin
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357

In [54]:
df.drop('g',axis=0)

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
t   0.582357  0.209079  0.989024  0.314500

In [55]:
df.shape

(5, 4)

In [56]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
g   0.351099  0.548193  0.478534  0.201357
t   0.582357  0.209079  0.989024  0.314500

In [57]:
df.drop('g',axis=0,inplace=True)

In [58]:
df

tejaswini   aashima    yogesh    pravin
a   0.339868  0.332858  0.556951  0.839451
c   0.777873  0.883521  0.680753  0.104139
f   0.754932  0.469042  0.202435  0.940436
t   0.582357  0.209079  0.989024  0.314500